# Generated by Django 3.2.9 on 2022-02-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20220225_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create1',
            new_name='createtable',
        ),
    ]
